### ISSUE TITLE
issues with file not found

### ISSUE THREAD

**Issue by webmsgr** [pericazivkovic/portablepython#34]
[log.log](https://github.com/pericazivkovic/portablepython/files/1485056/log.log)
see log.log for output!
When I goto the "output" folder, there is nothing there!

**Comment by pericazivkovic** [comment]
If you take a look ini the log file you provided you will see that whole bunch of files that need to be downloaded to make PP distribution were not found.  

Sninppet from the log file:

```
::  Downloading: pyserial-py3k-2.5.win32.exe
::  Verifying MD5 hash c7d770dede6f6c6197d9652a7658f18e for file pyserial-py3k-2.5.win32.exe
NOT FOUND    *****        C:\Users\User\AppData\Local\TempPortablePython.v.3.2.5.1.Build\binaries\pyserial-py3k-2.5.win32.exe
```

Because of that, at the end of script, the build process was aborted with: 

`Error in script "main.nsi" on line 101 -- aborting creation process`

That is the first thing you need to undestand - are the files that script tried to download available online or is it an issue with your network connection during script execution.

All dependency files (for 3.2 version) are listed here:https://github.com/pericazivkovic/portablepython/blob/master/3.2/settings.bat

**Comment by webmsgr** [comment]
i can download pyserial just fine
